### PR TITLE
Compress images, some more README fixes

### PR DESCRIPTION
**Pull request by RaptaG**
Tool used: https://imagecompressor.com/

Colors:

- `icon.png`, `folder.png`, `folder_open.png` -> 9 colors
- `example.png` -> 80 colors

### CODE REVIEW

**Comment by RaptaG** [comment]
Also, you should change the repo's description to:
```
Fabric mod that enhances the resource pack menu
```
Less is more

**Comment by enjarai** [comment]
I don't think its entirely nessecary to compress images that are this small already, did you make sure to do it losslessly?

**Comment by RaptaG** [comment]
> I don't think its entirely nessecary to compress images that are this small already, did you make sure to do it losslessly?

Yes I'm sure, many bytes were saved without destroying the quality

**Comment by RaptaG** [comment]
You can compare them yourself

**Comment by enjarai** [comment]
If theres no quality loss this seems good.

**Pull request merged**
